from typing import Any, Callable

class FastAPI:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def get(self, *args: Any, **kwargs: Any) -> Callable[..., Any]: ...
    def post(self, *args: Any, **kwargs: Any) -> Callable[..., Any]: ...
    def add_middleware(self, *args: Any, **kwargs: Any) -> None: ...

class HTTPException(Exception):
    def __init__(self, status_code: int, detail: Any = ...) -> None: ...

def Query(default: Any = ..., *args: Any, **kwargs: Any) -> Any: ...
