from typing import Any

class Response:
    def __init__(self, content: Any = ..., status_code: int = ..., headers: Any = ..., media_type: Any = ...) -> None: ...

class JSONResponse(Response): ...
class RedirectResponse(Response): ...
